server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: redis-master.dev.svc.cluster.local
      port: 6379

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: product-service
              uri: http://product-service.dev.svc.cluster.local:8080
              predicates:
                - Path=/api/products/**
              filters:
                - StripPrefix=2
                - TokenRelay
                - name: RequestRateLimiter
                  args:
                    "[redis-rate-limiter.replenishRate]": 5
                    "[redis-rate-limiter.burstCapacity]": 10
                    key-resolver: "#{@ipKeyResolver}"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.keycloak.svc.cluster.local:8080/realms/ecommerce

logging:
  level:
    "[org.springframework.cloud.gateway]": DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
