replicaCount: 1

image:
  repository: subhajit/ecommerce/api-gateway
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: api-gateway.local
      paths:
        - path: /
          pathType: Prefix

resources: {}
